export const styles = `
.dse-section{display:flex;flex-direction:column;gap:18px;width:100%;max-width:760px;color:var(--dsw-alias-label-primary)}
.dse-header{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.dse-eyebrow{margin:0 0 4px;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}.dse-title{margin:0;font-size:22px;line-height:30px;font-weight:600}.dse-subtle{margin:0;color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:20px}
.dse-actions{display:flex;flex-wrap:wrap;gap:8px}.dse-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.dse-card{min-width:0;padding:16px;border-radius:8px;background:var(--dsw-alias-bg-layer-3);box-shadow:var(--dsw-elevation-stroke)}.dse-card-wide{grid-column:1/-1}.dse-card h3{margin:0 0 10px;font-size:13px;line-height:20px;font-weight:600}.dse-value{margin:0;font-size:18px;line-height:26px;font-weight:600}.dse-meta{margin:4px 0 0;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}
.dse-list{display:flex;flex-direction:column;gap:8px;margin:0;padding:0;list-style:none}.dse-row{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:36px;padding:8px 0;border-bottom:.5px solid var(--dsw-alias-border-l2)}.dse-row:last-child{border-bottom:0}.dse-row-main{min-width:0}.dse-row-title{display:block;overflow:hidden;font-size:14px;line-height:20px;font-weight:500;text-overflow:ellipsis;white-space:nowrap}.dse-row-note{display:block;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}.dse-tags{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.dse-tag{display:inline-flex;min-height:20px;align-items:center;border-radius:6px;padding:1px 7px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);font-size:11px;line-height:18px}.dse-tag-accent{background:color-mix(in srgb,var(--dsw-alias-state-business-primary) 10%,transparent);color:var(--dsw-alias-state-business-primary)}
.dse-field{display:flex;flex-direction:column;gap:8px}.dse-field select{min-height:36px;border:1px solid var(--dsw-alias-border-l2);border-radius:6px;padding:0 10px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit}
.dse-status{padding:20px;border-radius:8px;background:var(--dsw-alias-bg-layer-3);color:var(--dsw-alias-label-tertiary);font-size:13px}.dse-error{color:var(--dsw-alias-state-error-primary)}.dse-plugin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.dse-plugin{display:flex;min-height:118px;flex-direction:column;gap:8px;padding:16px;border-radius:8px;background:var(--dsw-alias-bg-layer-3);box-shadow:var(--dsw-elevation-stroke)}.dse-plugin-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.dse-plugin h3{margin:0;font-size:15px}.dse-plugin p{display:-webkit-box;overflow:hidden;margin:0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px;-webkit-line-clamp:2;-webkit-box-orient:vertical}
@media(max-width:720px){.dse-grid,.dse-plugin-grid{grid-template-columns:1fr}.dse-card-wide{grid-column:auto}.dse-header{flex-direction:column}}
`
