/** Organization-scoped DSH profile that keeps the Web client while replacing personal providers. */
import { randomBytes } from 'node:crypto'
import { mkdir, rename, writeFile } from 'node:fs/promises'
import { isAbsolute, join } from 'node:path'
import { z } from 'zod'

const absolutePath = z.string().refine(isAbsolute)
export const enterpriseProfileConfig = z.object({
  home: absolutePath,
  frontendIndex: absolutePath.optional(),
  apiUrl: z.url(),
  organizationId: z.uuid(),
  keychainHelper: absolutePath,
  keychainAccount: z.string().min(1),
  defaultModel: z.string().min(1),
  plugins: z.object({
    llmFiles: absolutePath,
    gateway: absolutePath,
    sessionPersistence: absolutePath,
    enterpriseClient: absolutePath,
  }).strict(),
}).strict()
export type EnterpriseProfileConfig = z.infer<typeof enterpriseProfileConfig>

/** Resolve repository-build defaults used by source development and lifecycle tests. */
export function developmentEnterpriseProfile(root: string): Omit<EnterpriseProfileConfig, 'home'> {
  const base = absolutePath.parse(root)
  return {
    apiUrl: 'http://127.0.0.1:8787',
    frontendIndex: join(base, 'build', 'frontend', 'index.html'),
    organizationId: '00000000-0000-4000-8000-000000000001',
    keychainHelper: join(base, 'native', 'keychain'),
    keychainAccount: 'development-runtime',
    defaultModel: 'enterprise-unconfigured',
    plugins: {
      llmFiles: join(base, '..', '..', 'packages', 'llm', 'llm-files', 'lib', 'index.js'),
      gateway: join(base, 'lib', 'gateway-provider.js'),
      sessionPersistence: join(base, 'lib', 'session-provider.js'),
      enterpriseClient: join(base, '..', 'enterprise-client', 'lib', 'index.js'),
    },
  }
}

const quote = (value: string): string => JSON.stringify(value)

/** Render the enterprise-only overrides applied after the base and Web bundles. */
export function enterpriseProfilePatch(input: EnterpriseProfileConfig): string {
  const config = enterpriseProfileConfig.parse(input)
  const workspace = join(config.home, 'workspace')
  const frontendOverride = config.frontendIndex === undefined ? '' : `
- id: web-runtime
  config:
    openBrowser: false
    printUrl: true
    surfaceContext: true
    trustedHosts: []
    distIndex: ${quote(config.frontendIndex)}`
  return `# Generated by the Enterprise desktop host. Manual edits are replaced at the next login.${frontendOverride}
- id: llm-pi-ai
  disabled: true
- id: llm-deepseek
  disabled: true
- id: web-search-deepseek
  disabled: true
- id: session-persistence-jsonl
  disabled: true
- id: session-telemetry-otel
  disabled: true
- id: agent-default-model
  config:
    provider: enterprise
    model: ${quote(config.defaultModel)}
- id: sandbox-policy
  config:
    mode: read-only
    workspaceRoot: ${quote(workspace)}
- id: ui-settings-models
  disabled: true
- id: ui-settings-plugin-inventory
  disabled: true
- id: ui-settings-plugins
  disabled: true
- insert:
    - id: llm-files
      name: ${quote(config.plugins.llmFiles)}
    - id: enterprise-gateway
      name: ${quote(config.plugins.gateway)}
      config:
        apiUrl: ${quote(config.apiUrl)}
        keychainHelper: ${quote(config.keychainHelper)}
        keychainAccount: ${quote(config.keychainAccount)}
        requestTimeoutMs: 120000
        maxEventChars: 2097152
        maxResponseChars: 16777216
    - id: enterprise-session-persistence
      name: ${quote(config.plugins.sessionPersistence)}
      config:
        apiUrl: ${quote(config.apiUrl)}
        keychainHelper: ${quote(config.keychainHelper)}
        keychainAccount: ${quote(config.keychainAccount)}
        requestTimeoutMs: 30000
        maxResponseBytes: 16777216
    - id: enterprise-client
      name: ${quote(config.plugins.enterpriseClient)}
      inject: [connection]
      config:
        apiUrl: ${quote(config.apiUrl)}
        organizationId: ${quote(config.organizationId)}
        keychainHelper: ${quote(config.keychainHelper)}
        keychainAccount: ${quote(config.keychainAccount)}
        maxResponseBytes: 1048576
`
}

async function replace(path: string, contents: string): Promise<void> {
  const temporary = `${path}.${randomBytes(8).toString('hex')}.tmp`
  await writeFile(temporary, contents, { encoding: 'utf8', mode: 0o600, flag: 'wx' })
  await rename(temporary, path)
}

/** Materialize the generated startup-only profile before the runtime process starts. */
export async function provisionEnterpriseProfile(input: EnterpriseProfileConfig): Promise<void> {
  const config = enterpriseProfileConfig.parse(input)
  const profile = join(config.home, 'profiles', 'enterprise-desktop')
  await mkdir(join(config.home, 'workspace'), { recursive: true, mode: 0o700 })
  await mkdir(profile, { recursive: true, mode: 0o700 })
  await replace(join(profile, 'package.json'), JSON.stringify({
    name: '@deepseek-ai/dsh-enterprise-desktop-profile',
    private: true,
    type: 'module',
    dsh: { profile: { bundles: ['@deepseek-ai/dsh-base', '@deepseek-ai/dsh-web-app'], patchReload: 'startup' } },
  }, null, 2) + '\n')
  await replace(join(profile, 'cordis.patch.yml'), enterpriseProfilePatch(config))
}
